#!/bin/bash
#
# script to pull info about a given domain

DOMAIN=$1

#show DNS info for domain
getips () {
    DIGOPTS='+noall +answer -t'
    DIG="$(which dig) $DIGOPTS"

    for RECORD in ns mx a cname aaaa txt srv
    do
	#printf "%s\n%s\n" ""${RECORD^^}"" "-------------------------"
	printf "${RECORD^^} %s\n" "-------------------------"
	#echo ${RECORD^^}
	#echo -------------------------
	$DIG $RECORD "$DOMAIN"
    done
}

# show usage information 
showuse () {
    echo "Usage: $0 <domain>"
}

[ -n "$DOMAIN" ] || showuse

# FIXME -- `whois -H` is not valid on macOS, consider finding another way to supress
#	    legal output from whois for mac

#show whois info for domain
get_whois () {
    _myos=$(uname)
    case $_myos in
	Linux)
	    WHOIS="$(which whois) -H "
	    ;;
	Darwin)
	    WHOIS="$(which whois) "
	    ;;
	*)
	    ;;
    esac

    #show message if no whois data found otherwise output whois to screen
    if [[ "$WHOIS" == *'no entries found'* ]] 
    then
       printf '%s\n\%s' "No WHOIS available for" "$DOMAIN"
       exit 1
    else
	$WHOIS "$DOMAIN"
    fi
}

get_whois
#getips
