#!/bin/bash
#
# script to pull info about a given domain

DOMAIN=$1

#show DNS info for domain
getips () {
    DIGOPTS='+noall +answer -t'
    DIG="$(which dig) $DIGOPTS"

    for RECORD in ns mx a cname aaaa txt srv
    do
	echo $RECORD | awk '{print toupper($0)}'
	echo -------------------------
	$DIG $RECORD $DOMAIN
    done
}

# show usage information 
if [ -z $DOMAIN ]; 
then
   echo "Usage: $0 <domain>";
   exit 1
fi

# FIXME -- `whois -H` is not valid on macOS, consider finding another way to supress
#	    legal output from whois for mac

#show whois info for domain
get_whois () {
_myos=$(uname)
case $_myos in
    Linux)
	WHOIS="$(which whois) -H $DOMAIN"
	;;
    Darwin)
	WHOIS="$(which whois) $DOMAIN"
	;;
    *)
	;;
esac

if $WHOIS |grep -q "no entries found";
then
   echo "No WHOIS available for $DOMAIN";
   exit 1
else
    $WHOIS $DOMAIN
fi
}

get_whois
getips
